# Generated by Django 4.1.2 on 2023-05-13 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19d1dad9-dcc7-4de5-9a18-568b356f77be'), editable=False, primary_key=True, serialize=False),
        ),
    ]
