# Generated by Django 4.1.2 on 2023-05-13 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1377b543-467c-4885-b0e6-4946c88cadf2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
