# Generated by Django 4.1.2 on 2023-05-13 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('baa3460c-e100-40e0-8671-7b9123a56dca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bfe56152-169e-46db-8abb-ba0fee85cbf3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
