# Generated by Django 4.1.2 on 2023-05-13 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_alter_answer_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad5cf128-6abd-4c2a-846c-d28058f14625'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25c62b8e-95ff-4cb2-815d-8ac29284c47c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
