# Generated by Django 4.1.2 on 2023-05-13 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_alter_answer_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44993794-cbb8-4c4f-badf-f36bcadb55e8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1bfc9cc2-edb4-451f-875e-919dd355072c'), primary_key=True, serialize=False),
        ),
    ]
