# Generated by Django 4.1.2 on 2023-05-13 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_alter_answer_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b84ae65-189e-47ef-964c-32767bb8ec7c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30004c93-79b9-47e2-bd28-90b25c5b4ece'), primary_key=True, serialize=False),
        ),
    ]
