# Generated by Django 4.1.2 on 2023-05-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0006_alter_answer_id_alter_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='helpful',
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
