# Generated by Django 4.1.2 on 2023-05-14 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_alter_profile_id_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 5, 14, 15, 36, 23, 41128))),
                ('on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rewardprofile', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RewardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('on', models.DateTimeField(auto_now=True)),
                ('reward_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.profile')),
            ],
        ),
    ]
